name       : yubikey-personalization
version    : 1.19.3
release    : 11
source     :
    - https://github.com/Yubico/yubikey-personalization/archive/v1.19.3.tar.gz : a59273938fb9d1e1e059e319e2d73bac2f121dad53b76efb49b1631839cb2afc
license    : BSD-2-Clause
component  : security
summary    : A library and command line tool used to personalize YubiKeys.
description: |
    The YubiKey Personalization package contains a library and command line tool used to personalize (i.e., set a AES key) YubiKeys.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(json-c)
    - pkgconfig(udev)
    - asciidoc
    - libyubikey-devel
setup      : |
    %reconfigure --disable-static --with-udevrulesdir=/usr/lib64/udev/rules.d/
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
