name       : yubikey-personalization
version    : 1.18.1
release    : 7
source     :
    - https://developers.yubico.com/yubikey-personalization/Releases/ykpers-1.18.1.tar.gz : 9ffdb938121a867aa0b350b49daff5807884c2268dfe6d245d133474cd9c5256
license    : BSD-2-Clause
component  : security
summary    : A library and command line tool used to personalize YubiKeys.
description: |
    The YubiKey Personalization package contains a library and command line tool used to personalize (i.e., set a AES key) YubiKeys.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(json-c)
    - pkgconfig(udev)
    - asciidoc
    - libyubikey-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -d $installdir/etc/udev/rules.d
    install -D -m755 $workdir/*-yubikey.rules $installdir/etc/udev/rules.d/
